name: 'Github Actions Weather Bot'

on:
  push:

jobs:
  get-weather-report-and-send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather report'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ='Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Guangzhou Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: zongkai.liang@gmail.com
          from: Github Actions
          content_type: text/html
